### ISSUE TITLE
script.module.astral - missing modules

### ISSUE THREAD

**Issue by gibxxi** [semool/script.module.astral#1]
Running the "Arctic Zephyr MOD - Autocolors" plugin on launch, started generating errors again recently. Looking at the kodi.log file, I have determined it's not the Autocolors plugin causing the issue, but rather the 'Astral' plugin it uses as a dependency.

The following is displayed in the log:

2024-08-14 08:13:58.114 T:18884   error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'ModuleNotFoundError'>
                                                   Error Contents: No module named 'backports'
                                                   Traceback (most recent call last):
                                                     File "D:\Kodi Media Center\portable_data\addons\script.module.astral\lib\astral\__init__.py", line 52, in <module>
                                                       import zoneinfo
                                                   ModuleNotFoundError: No module named 'zoneinfo'
                                                   
                                                   During handling of the above exception, another exception occurred:
                                                   
                                                   Traceback (most recent call last):
                                                     File "D:\Kodi Media Center\portable_data\addons\script.arctic.zephyr.mod.autocolors\service.py", line 6, in <module>
                                                       from resources.lib.utils import *
                                                     File "D:\Kodi Media Center\portable_data\addons\script.arctic.zephyr.mod.autocolors\resources\lib\utils.py", line 9, in <module>
                                                       from astral import LocationInfo
                                                     File "D:\Kodi Media Center\portable_data\addons\script.module.astral\lib\astral\__init__.py", line 54, in <module>
                                                       from backports import zoneinfo
                                                   ModuleNotFoundError: No module named 'backports'
                                                   -->End of Python script error report<--

This mod obviously isn't seeing massive usage, as this would have already been flagged by someone else, but I'm reporting it regardless.

Dan / Gib.

**Comment by semool** [comment]
Than you have it not installed correctly. script.module.backports.zoneinfo is listed in the addon.xml as a requierment.
https://rsync.kodi.tv/addons/piers/script.module.backports.zoneinfo/
